security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: mail
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|img)/
            security: false
        inscription:
            pattern: ^/api/users/enregister$
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
        #login:
         #   pattern:  ^/api/login_check
          #  stateless: true
           # anonymous: true
            #json_login:
             #   provider: app_user_provider
              #  check_path: /api/login_check
               # username_path: mail
                #password_path: mdp
                #success_handler: lexik_jwt_authentication.handler.authentication_success
                #failure_handler: lexik_jwt_authentication.handler.authentication_failure
            #guard:
             #   authenticators:
              #      - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

        #api:
         #   pattern:   ^/api
          #  stateless: true
           # guard:
            #    authenticators:
             #       - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/api, roles: ROLE_CNX }
